8fit/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls


urlpatterns = [
    url(r'^django-admin/', admin.site.urls),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),


    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r'', include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

from wagtail.core.models import Page


class HomePage(Page):
    pass

promos/models.py
from django.db import models

from modelcluster.fields import ParentalKey

from wagtail.core import blocks
from wagtail.images.blocks import ImageChooserBlock
from wagtail.core.models import Page, Orderable
from wagtail.core.fields import RichTextField, StreamField
from wagtail.admin.edit_handlers import FieldPanel, MultiFieldPanel, InlinePanel, StreamFieldPanel
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.search import index
from wagtail.snippets.models import register_snippet
from wagtailcolumnblocks.blocks import ColumnsBlock


@register_snippet
class PromoPlan(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=500)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Promo plan'
        verbose_name_plural = 'Promo Plans'


# Content blocks that will be used in the columngrid block
class CommonBlocks(blocks.StreamBlock):
    content = blocks.RichTextBlock(group="Common")

# Column Types
class ColumnBlocks(blocks.StreamBlock):
    column_1_1 = ColumnsBlock(
        CommonBlocks(),
        ratios=(1, 1),
        label="Two halves",
        group="Columns",
    )
    column_2_1 = ColumnsBlock(
        CommonBlocks(max_num=1),
        ratios=(2, 1),
        label="Two thirds/One third",
        group="Columns",
    )
    column_1_1_1 = ColumnsBlock(
        CommonBlocks(),
        ratios=(1, 1, 1),
        label="Three thirds",
        group="Columns",
    )


class AllBlocks(ColumnBlocks, CommonBlocks):
    pass



""" Highlight Colors:

    Used for changing colours of headers/links to liven up pages
    It's also possible to make these dynamically created choices.
"""
COLOR_CHOICES = (
    ('green', 'Green'),
    ('orange', 'Orange'),
    ('red', 'Red'),
)


class ContentBlock(blocks.StructBlock):
    feature_name = blocks.CharBlock()
    heading = blocks.CharBlock()
    content = blocks.RichTextBlock(features=['h4', 'bold', 'italic', 'link', 'ol', 'ul'])
    screenshot = ImageChooserBlock()
    highlight_color = blocks.ChoiceBlock(
        choices=COLOR_CHOICES,
        required=False,
        blank=True, null=True)
    feautre_icon = ImageChooserBlock(help_text="For linking to the featured section")
    slug = blocks.CharBlock()

    class Meta:
        icon = 'user'
        form_classname = 'content-block struct-block'


class PromoLandingPage(Page):
    TMP_CURRENCIES = (
        ('USD', '$'),
        ('GBP', '£'),
        ('EUR', '€'),
    )
    hero_title = models.CharField(max_length=100)
    hero_subtitle = models.CharField(max_length=200, blank=True, null=True)
    overview = StreamField(
        blocks.StreamBlock([
        ('freeform', blocks.RichTextBlock()),
        ('two_three_column_grid', ColumnBlocks())
    ], max_num=3), null=True, blank=True
    )
    body = StreamField(
        blocks.StreamBlock([
        ('content', ContentBlock())
    ], max_num=3), verbose_name="Features"
    )
    extra_content = StreamField(
        blocks.StreamBlock([
        ('freeform', blocks.RichTextBlock()),
        ('two_three_column_grid', ColumnBlocks())
    ], max_num=3), null=True, blank=True
    )
    hero_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )
    plan = models.ForeignKey(
        PromoPlan,
        null=True,
        blank=True,
        on_delete=models.SET_NULL
    )
    price = models.DecimalField(decimal_places=2, max_digits=10)
    currency = models.CharField(max_length=3, choices=TMP_CURRENCIES)
    promo_duration = models.DateTimeField(
        help_text="Set the time when you want this to expire.",
        blank=True,
        null=True
    )
    coupon = models.CharField(max_length=50, blank=True, null=True)
    benefits = RichTextField(features=['h4', 'bold', 'italic', 'ol', 'ul'], blank=True, null=True)
    CTA = models.CharField(max_length=200, default="Start Your Plan Now.")

    created_date = models.DateTimeField(editable=False, auto_now_add=True)
    modified_date = models.DateTimeField(editable=False, db_index=True, auto_now=True)

    content_panels = [
        ImageChooserPanel('hero_image'),
        FieldPanel('title'),
        FieldPanel('hero_title'),
        FieldPanel('hero_subtitle'),
        StreamFieldPanel('overview'),
        StreamFieldPanel('body'),
        StreamFieldPanel('extra_content'),
        MultiFieldPanel(
        [
            FieldPanel('plan'),
            FieldPanel('price'),
            FieldPanel('currency'),
            FieldPanel('coupon'),
            FieldPanel('promo_duration'),
            FieldPanel('CTA'),
            FieldPanel('benefits')
        ],
        heading="Promo Plan Details",
        classname="collapsible"
        ),
    ]

promos/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render

from wagtail.core.models import Page

8fit/templates/base.html
{% load static wagtailuserbar %}

<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8" />
        <meta name="robots" content="noindex, nofollow">
        <title>
            {% block title %}
                {% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}
            {% endblock %}
            {% block title_suffix %}
                {% with self.get_site.site_name as site_name %}
                    {% if site_name %}- {{ site_name }}{% endif %}
                {% endwith %}
            {% endblock %}
        </title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {# Global stylesheets #}
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/8fit.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>

    <body class="{% block body_class %}{% endblock %}">

        {% block content %}{% endblock %}

        {# Global javascript #}
        <script type="text/javascript" src="{% static 'js/mysite.js' %}"></script>

        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
    </body>
</html>

home/templates/home/home_page.html
{% extends "base.html" %}

{% block body_class %}template-homepage{% endblock %}

{% block content %}
<div class="container text-center py-5">

    <h1>Demo site for 8fit.</h1>
    <h3> By Onyeka Aghanenu</h3>

    <p>View the admin <a href="{% url 'wagtailadmin_home' %}">here</a>.</p>

    <p>Sample <a href="/get-in-shape/">promo page</a></p>
  </div>

{% endblock %}

promos/templates/promos/blocks/feature_links.html
{% load wagtailimages_tags %}
{% image cblock.value.feautre_icon fill-200x200 as icon %}

      <div class="col">
        <div class="px-3 pt-3  pb-0">
          <a href="#{{ cblock.value.slug }}">
          <img class="img-fluid " src="{{ icon.url }}" alt="">
          <h3 class="text-primary">{{ cblock.value.feature_name }}</h3>
        </a>
        </div>
      </div>

promos/templates/promos/blocks/landing_content.html
{% load wagtailimages_tags %}
{% image cblock.value.screenshot height-400 as screenshot %}

<section id="{{ cblock.value.slug }}" class="feature border-bottom">
  <div class="container">
    <div class="row align-items-center accent-{{ cblock.value.highlight_color }}">
      <div class="col-lg-6  {% if forloop.counter|divisibleby:"2" %} order-lg-1{% else %}order-lg-2 {% endif %}">
        <div class="px-5 pt-5  pb-0  {% if forloop.counter|divisibleby:"2" %} text-md-right {% endif %}">
          <img class="img-fluid " src="{{ screenshot.url }}" alt="">
        </div>
      </div>
      <div class="col-lg-6 {% if forloop.counter|divisibleby:"2" %} order-lg-2{% else %}order-lg-1 {% endif %}">
        <div class="p-5  {% if not forloop.counter|divisibleby:"2" %} text-md-right {% endif %}">
          <h2 class="section-header">{{ cblock.value.heading }}</h2>
           {{ cblock.value.content|linebreaks }}
        </div>
      </div>
    </div>
  </div>
</section>

promos/templates/promos/blocks/payment_form.html
{% block extra_css%}
<style>

.example.example2 {
  background-color: #fff;
}

.example.example2 * {
  font-size: 16px;
  font-weight: 500;
}

.example.example2 .row {
  display: -ms-flexbox;
  display: flex;
  flex-wrap: nowrap !important;
  margin: 0 5px 10px;
}

.example.example2 .field {
  position: relative;
  width: 100%;
  height: 50px;
  margin: 0 10px;
}

.example.example2 .field.half-width {
  width: 50%;
}

.example.example2 .field.quarter-width {
  width: calc(25% - 10px);
}

.example.example2 .baseline {
  position: absolute;
  width: 100%;
  height: 1px;
  left: 0;
  bottom: 0;
  background-color: #cfd7df;
  transition: background-color 0.3s cubic-bezier(0.165, 0.84, 0.44, 1);
}

.example.example2 label {
  position: absolute;
  width: 100%;
  left: 0;
  bottom: 8px;
  color: #cfd7df;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  transform-origin: 0 50%;
  cursor: text;
  transition-property: color, transform;
  transition-duration: 0.3s;
  transition-timing-function: cubic-bezier(0.165, 0.84, 0.44, 1);
}

.example.example2 .input {
  position: absolute;
  width: 100%;
  left: 0;
  bottom: 0;
  padding-bottom: 7px;
  color: #32325d;
  background-color: transparent;
}

.example.example2 .input::-webkit-input-placeholder {
  color: transparent;
  transition: color 0.3s cubic-bezier(0.165, 0.84, 0.44, 1);
}

.example.example2 .input::-moz-placeholder {
  color: transparent;
  transition: color 0.3s cubic-bezier(0.165, 0.84, 0.44, 1);
}

.example.example2 .input:-ms-input-placeholder {
  color: transparent;
  transition: color 0.3s cubic-bezier(0.165, 0.84, 0.44, 1);
}

.example.example2 .input.StripeElement {
  opacity: 0;
  transition: opacity 0.3s cubic-bezier(0.165, 0.84, 0.44, 1);
  will-change: opacity;
}

.example.example2 .input.focused,
.example.example2 .input:not(.empty) {
  opacity: 1;
}

.example.example2 .input.focused::-webkit-input-placeholder,
.example.example2 .input:not(.empty)::-webkit-input-placeholder {
  color: #cfd7df;
}

.example.example2 .input.focused::-moz-placeholder,
.example.example2 .input:not(.empty)::-moz-placeholder {
  color: #cfd7df;
}

.example.example2 .input.focused:-ms-input-placeholder,
.example.example2 .input:not(.empty):-ms-input-placeholder {
  color: #cfd7df;
}

.example.example2 .input.focused + label,
.example.example2 .input:not(.empty) + label {
  color: #aab7c4;
  transform: scale(0.85) translateY(-25px);
  cursor: default;
}

.example.example2 .input.focused + label {
  color: #24b47e;
}

.example.example2 .input.invalid + label {
  color: #ffa27b;
}

.example.example2 .input.focused + label + .baseline {
  background-color: #24b47e;
}

.example.example2 .input.focused.invalid + label + .baseline {
  background-color: #e25950;
}

.example.example2 input, .example.example2 button {
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
  outline: none;
  border-style: none;
}

.example.example2 input:-webkit-autofill {
  -webkit-text-fill-color: #e39f48;
  transition: background-color 100000000s;
  -webkit-animation: 1ms void-animation-out;
}

.example.example2 .StripeElement--webkit-autofill {
  background: transparent !important;
}

.example.example2 input, .example.example2 button {
  -webkit-animation: 1ms void-animation-out;
}

/* .example.example2 button {
  display: block;
  width: calc(100% - 30px);
  height: 40px;
  margin: 40px 15px 0;
  background-color: #24b47e;
  border-radius: 4px;
  color: #fff;
  text-transform: uppercase;
  font-weight: 600;
  cursor: pointer;
} */

.example.example2 input:active {
  background-color: #159570;
}

.example.example2 .error svg {
  margin-top: 0 !important;
}

.example.example2 .error svg .base {
  fill: #e25950;
}

.example.example2 .error svg .glyph {
  fill: #fff;
}

.example.example2 .error .message {
  color: #e25950;
}

.example.example2 .success .icon .border {
  stroke: #abe9d2;
}

.example.example2 .success .icon .checkmark {
  stroke: #24b47e;
}

.example.example2 .success .title {
  color: #32325d;
  font-size: 16px !important;
}

.example.example2 .success .message {
  color: #8898aa;
  font-size: 13px !important;
}

.example.example2 .success .reset path {
  fill: #24b47e;
}
</style>
{% endblock %}
 <main>
   <section class="container-lg">

<div class="cell example example2">
  <h6 class="text-muted text-uppercase">Card Information</h6>

     <form>

       <div class="row">
         <div class="field">
           <div id="example2-card-number" class="input empty"></div>
           <label for="example2-card-number" data-tid="elements_examples.form.card_number_label">Card number</label>
           <div class="baseline"></div>
         </div>
       </div>
       <div class="row">
         <div class="field half-width">
           <div id="example2-card-expiry" class="input empty"></div>
           <label for="example2-card-expiry" data-tid="elements_examples.form.card_expiry_label">Expiration</label>
           <div class="baseline"></div>
         </div>
         <div class="field half-width">
           <div id="example2-card-cvc" class="input empty"></div>
           <label for="example2-card-cvc" data-tid="elements_examples.form.card_cvc_label">CVC</label>
           <div class="baseline"></div>
         </div>
       </div>
       <div class="btn-container text-center">
     <button class="rounded-pill btn btn-lg btn-primary my-4 text-center" type="submit" data-tid="elements_examples.form.pay_button">{{ page.CTA }}</button>
   </div>

       <div class="error" role="alert"><svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" viewBox="0 0 17 17">
           <path class="base" fill="#000" d="M8.5,17 C3.80557963,17 0,13.1944204 0,8.5 C0,3.80557963 3.80557963,0 8.5,0 C13.1944204,0 17,3.80557963 17,8.5 C17,13.1944204 13.1944204,17 8.5,17 Z"></path>
           <path class="glyph" fill="#FFF" d="M8.5,7.29791847 L6.12604076,4.92395924 C5.79409512,4.59201359 5.25590488,4.59201359 4.92395924,4.92395924 C4.59201359,5.25590488 4.59201359,5.79409512 4.92395924,6.12604076 L7.29791847,8.5 L4.92395924,10.8739592 C4.59201359,11.2059049 4.59201359,11.7440951 4.92395924,12.0760408 C5.25590488,12.4079864 5.79409512,12.4079864 6.12604076,12.0760408 L8.5,9.70208153 L10.8739592,12.0760408 C11.2059049,12.4079864 11.7440951,12.4079864 12.0760408,12.0760408 C12.4079864,11.7440951 12.4079864,11.2059049 12.0760408,10.8739592 L9.70208153,8.5 L12.0760408,6.12604076 C12.4079864,5.79409512 12.4079864,5.25590488 12.0760408,4.92395924 C11.7440951,4.59201359 11.2059049,4.59201359 10.8739592,4.92395924 L8.5,7.29791847 L8.5,7.29791847 Z"></path>
         </svg>
         <span class="message"></span></div>
     </form>
     <div class="success">
       <div class="icon">
         <svg width="84px" height="84px" viewBox="0 0 84 84" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
           <circle class="border" cx="42" cy="42" r="40" stroke-linecap="round" stroke-width="4" stroke="#000" fill="none"></circle>
           <path class="checkmark" stroke-linecap="round" stroke-linejoin="round" d="M23.375 42.5488281 36.8840688 56.0578969 64.891932 28.0500338" stroke-width="4" stroke="#000" fill="none"></path>
         </svg>
       </div>
       <h3 class="title" data-tid="elements_examples.success.title">Payment successful</h3>
       <p class="message"><span data-tid="elements_examples.success.message">Thanks for trying Stripe Elements. No money was charged, but we generated a token: </span><span class="token">tok_189gMN2eZvKYlo2CwTBv9KKh</span></p>
       <a class="reset" href="#">
         <svg width="32px" height="32px" viewBox="0 0 32 32" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
           <path fill="#000000" d="M15,7.05492878 C10.5000495,7.55237307 7,11.3674463 7,16 C7,20.9705627 11.0294373,25 16,25 C20.9705627,25 25,20.9705627 25,16 C25,15.3627484 24.4834055,14.8461538 23.8461538,14.8461538 C23.2089022,14.8461538 22.6923077,15.3627484 22.6923077,16 C22.6923077,19.6960595 19.6960595,22.6923077 16,22.6923077 C12.3039405,22.6923077 9.30769231,19.6960595 9.30769231,16 C9.30769231,12.3039405 12.3039405,9.30769231 16,9.30769231 L16,12.0841673 C16,12.1800431 16.0275652,12.2738974 16.0794108,12.354546 C16.2287368,12.5868311 16.5380938,12.6540826 16.7703788,12.5047565 L22.3457501,8.92058924 L22.3457501,8.92058924 C22.4060014,8.88185624 22.4572275,8.83063012 22.4959605,8.7703788 C22.6452866,8.53809377 22.5780351,8.22873685 22.3457501,8.07941076 L22.3457501,8.07941076 L16.7703788,4.49524351 C16.6897301,4.44339794 16.5958758,4.41583275 16.5,4.41583275 C16.2238576,4.41583275 16,4.63969037 16,4.91583275 L16,7 L15,7 L15,7.05492878 Z M16,32 C7.163444,32 0,24.836556 0,16 C0,7.163444 7.163444,0 16,0 C24.836556,0 32,7.163444 32,16 C32,24.836556 24.836556,32 16,32 Z"></path>
         </svg>
       </a>
     </div>


   </div>
 </section>
</main>

promos/templates/promos/promo_landing_page.html
{% extends "base.html" %}
{% load static wagtailcore_tags %}
{% load wagtailcore_tags %}
{% load wagtailimages_tags %}

{% block body_class %}template-landing{% endblock %}
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/stripe.css' %}">

{% endblock %}

{% block title %}{{ page.title }}{% endblock %}

{% block content %}
{% image page.hero_image original as hero_image %}
<header class="masthead text-center" style="background:url('{{ hero_image.url }}') no-repeat;">
   <div class="masthead-content">
     <div class="container py-5 rounded">
       <h2 class="masthead-heading mb-0">{{ page.hero_title }}</h2>
       <h4 class="mb-0 text-primary">{{ page.hero_subtitle }}</h4>
       <a href="#purchase" class="btn btn-primary btn-xl rounded-pill mt-5">{{ page.CTA }}</a>
     </div>
   </div>

 </header>
 {% if page.overview %}
 <section id="overview" class="bg-white border-bottom">
   <div class="container  py-5 d-block text-center ">
     {{ page.overview }}
     <div class="row d-flex">
     {% for cblock in page.body %}
      {% include 'promos/blocks/feature_links.html' %}
    {% endfor %}
  </div>

 </div>
</section>
 {% endif %}

 {% for cblock in page.body %}

  {% include 'promos/blocks/landing_content.html' %}
{% endfor %}

{% if page.extra_content %}
<section id="overview" class="bg-white border-bottom">
  <div class="container  py-5 d-block text-center ">
    {{ page.extra_content }}
  </div>
</section>
{% endif %}
<!-- Payment Block -->
<section id="purchase" class="bg-light pt-4">
  <div class="container bg-white ">
    <div class="row">
      <div class="col-md-4 border-right">
        <div class="pt-5 d-flex justify-content-center align-items-center">
          <h1 class="text-primary d-inline-block">8fit </h1><span class="ml-1 badge bg-primary text-white d-inline-block">PRO</span></h1>
        </div>
        <div class="text-center ">
          <h3>{{ page.get_currency_display }}{{ page.price}}</h3>
          {% if page.benefits %}
          <div class="pt-2 benefits">
          {{ page.benefits|safe }}
        </div>
          {% endif %}
        </div>
      </div>
      <div class="col-md-8 ">
        <div class="p-5">
          <div class="text-center">
            {{ pa}}

        </div>
        <hr/>
           {{ cblock.value.content|linebreaks }}
           {% include 'promos/blocks/payment_form.html'%}
        </div>
      </div>
    </div>
  </div>
</section>

 <!-- Footer -->
 <footer class="py-5 bg-light">
   <div class="container">
     <p class="m-0 text-center text-muted small">Copyright &copy; 8fit 2018</p>
   </div>
   <!-- /.container -->
 </footer>

{% endblock %}

{% block extra_js %}
<script src="http://js.stripe.com/v3/"></script>

<script>
// Create a Stripe client.

(function() {
  'use strict';
  var stripe = Stripe('pk_test_PSxs0lNupNljq4dbyG9NN30g');

  var elements = stripe.elements({
    fonts: [
      {
        cssSrc: 'https://fonts.googleapis.com/css?family=Source+Code+Pro',
      },
    ],
    // Stripe's examples are localized to specific languages, but if
    // you wish to have Elements automatically detect your user's locale,
    // use `locale: 'auto'` instead.
    locale: window.__exampleLocale
  });

  // Floating labels
  var inputs = document.querySelectorAll('.cell.example.example2 .input');
  Array.prototype.forEach.call(inputs, function(input) {
    input.addEventListener('focus', function() {
      input.classList.add('focused');
    });
    input.addEventListener('blur', function() {
      input.classList.remove('focused');
    });
    input.addEventListener('keyup', function() {
      if (input.value.length === 0) {
        input.classList.add('empty');
      } else {
        input.classList.remove('empty');
      }
    });
  });

  var elementStyles = {
    base: {
      color: '#32325D',
      fontWeight: 500,
      fontFamily: 'Source Code Pro, Consolas, Menlo, monospace',
      fontSize: '16px',
      fontSmoothing: 'antialiased',

      '::placeholder': {
        color: '#CFD7DF',
      },
      ':-webkit-autofill': {
        color: '#e39f48',
      },
    },
    invalid: {
      color: '#E25950',

      '::placeholder': {
        color: '#FFCCA5',
      },
    },
  };

  var elementClasses = {
    focus: 'focused',
    empty: 'empty',
    invalid: 'invalid',
  };

  var cardNumber = elements.create('cardNumber', {
    style: elementStyles,
    classes: elementClasses,
  });
  cardNumber.mount('#example2-card-number');

  var cardExpiry = elements.create('cardExpiry', {
    style: elementStyles,
    classes: elementClasses,
  });
  cardExpiry.mount('#example2-card-expiry');

  var cardCvc = elements.create('cardCvc', {
    style: elementStyles,
    classes: elementClasses,
  });
  cardCvc.mount('#example2-card-cvc');

  registerElements([cardNumber, cardExpiry, cardCvc], 'example2');
})();
</script>
{% endblock %}